### ISSUE TITLE
Use Pre-Commit Hooks only?

### ISSUE THREAD

**Issue by tzehe** [rudikershaw/git-build-hook#16]
Hi, 

I discovered this project today and wanted to say thank you. I try to configure this for my team but we only need a pre-commit hook todo some formatting before commiting. 
It seems to still run all the hook even if I only specify the pre-commit hook.
Am I missing something? 

```
<plugin>
        <groupId>com.rudikershaw.gitbuildhook</groupId>
        <artifactId>git-build-hook-maven-plugin</artifactId>
        <version>3.0.0</version>
        <configuration>
          <installHooks>
            <pre-commit>etc/git-hooks/pre-commit-hooks/format.sh</pre-commit>
          </installHooks>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>install</goal>
            </goals>
          </execution>
        </executions>
</plugin>

```

**Comment by jjlharrison** [comment]
This plugin only installs the hook, if there are other hooks installed, it is Git itself that is running them.

**Comment by tzehe** [comment]
Ok, not sure if I exactly understand but what I thought is that instead of downloading all the hooks and configure them I can also select the once I want to 'install'. This was also explained in the Readme. Or what is the reason for the separat <installHooks>?

**Comment by rudikershaw** [comment]
Hi there,

The separate `installHook` configurations (e.g. `pre-commit`) simply copy the file you specify into the `.git/hooks` directory and rename it to the corresponding hook name. It will not clear out the `.git/hooks` directory, or remove any hooks that are already installed.

If you need to do that it may be better to use the `configure` goal to change the `core.hooksPath`. By telling git that another directory is to act as your hooks directory you can effectively ignore any already installed hooks for this project.

```
<plugin>
      <groupId>com.rudikershaw.gitbuildhook</groupId>
      <artifactId>git-build-hook-maven-plugin</artifactId>
      <version>3.0.0</version>
      <configuration>
        <gitConfig>
          <core.hooksPath>hooks-directory/</hooksPath>
        </gitConfig>
      </configuration>
      <executions>
        <execution>
          <goals> 
            <goal>configure</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
```
If you want this method to work however, you will need the files in your custom git hooks directory to have the appropriate hook names, for example `pre-commit` in your case.
