### ISSUE TITLE
Using this plugin in a SBT project

### ISSUE THREAD

**Issue by iamsmkr** [rudikershaw/git-build-hook#29]
Is there any way to use this plugin in a SBT project? If not, would you be willing to add support for it?

**Comment by rudikershaw** [comment]
Hi there, 

I'm not veryfamiliar with SBT, but [this answer from an SBT contributor seems to indicate that it is not possible](https://stackoverflow.com/a/26655617/2182928) unless you want to pull the project onto the classpath manually and manually call its methods. I suspect that would be more work than it is worth for you.

I am sorry to say that there appears to be no simple way of making a maven plugin compatible with an SBT plugin. This repository would not be able to support it. It would require a separate SBT plugin project.
