### ISSUE TITLE
Disable on CI

### ISSUE THREAD

**Issue by jhonynet** [rudikershaw/git-build-hook#32]
Hi!
There are some cases when this plugin needs to be disabled, for example, in continuous integration environment that does a git shallow clone and there is no need to configure any hook.

Maybe an environment variable that if is present the plugin won't run?

Regards!

**Comment by rudikershaw** [comment]
Hi there, I expect the feature you need already exists in Maven and doesn't need any changes to this plugin.

You can add Maven profiles to your project pom.xml. Simply set up a profile where the plugin is not active and run the build using that profile in your CI.

https://maven.apache.org/guides/introduction/introduction-to-profiles.html
