### ISSUE TITLE
Fails to initialize repo if using worktrees on windows

### ISSUE THREAD

**Issue by summersb** [rudikershaw/git-build-hook#54]
When running mvn compile I receive the following error

[ERROR] Failed to execute goal com.rudikershaw.gitbuildhook:git-build-hook-maven-plugin:3.4.1:configure (default) on project recap-parent: Could not find or initialise a local git repository. A repository is required.: repository not found: {mypath}\repo.git\worktrees\{branchname} -> [Help 1]

**Comment by summersb** [comment]
created a PR https://github.com/rudikershaw/git-build-hook/pull/55

**Comment by rudikershaw** [comment]
Good catch, and thanks for the contribution.

**Comment by rudikershaw** [comment]
I've merged in the changes. I don't have a ETA for a release of the changes to a new version, but I hope to push out a release soon (it's been too long). I'll leave the issue open until the release.

**Comment by rudikershaw** [comment]
This change has been released in 3.5.0. Closing as completed.
